name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"          
      - name: Clone Repo
        run: |
          WORKSPACE_PATH=$(pwd)/${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}/$(openssl rand -base64 8)
          echo WORKSPACE_PATH=${WORKSPACE_PATH} | tee -a ${GITHUB_ENV}
          mkdir -p $WORKSPACE_PATH
          cd $WORKSPACE_PATH
          git clone https://token:${{ secrets.TOKEN_ELOFUN }}@github.com/elofun/greatBunny.git .
      - name: build docker
        run: |
          cd $WORKSPACE_PATH
          docker build -t nodejs/v1 .
      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push dockerhub
        run: |
          docker tag nodejs/v1:latest kukhanh0812/nginx-proxy:game-0.0.2
          docker push kukhanh0812/nginx-proxy:game-0.0.2
